### ISSUE TITLE
dotnet-isolated: remove static keyword from C# template

### ISSUE THREAD

**Issue by prabh-62** [Azure/azure-functions-templates#1034]
## System Info

```shell
❯ dotnet --list-sdks
5.0.201 [/usr/local/share/dotnet/sdk]

❯ func --version
3.0.3388

```

## Steps to reproduce

```shell
❯ mkdir Turtle && cd Turtle
❯ func init --worker-runtime dotnetIsolated
❯ func new --template "HTTP trigger" --name Greet
```

```csharp
{
    public static class Greet
    {
        [Function("Greet")]
        public static HttpResponseData Run([HttpTrigger(AuthorizationLevel.Function, "get", "post")] HttpRequestData req,
            FunctionContext executionContext)
        {
            var response = req.CreateResponse(HttpStatusCode.OK);
            response.Headers.Add("Content-Type", "text/plain; charset=utf-8");

            response.WriteString("Welcome to Azure Functions!");

            return response;
        }
    }
}
```

The newly created templates have `static` keyword in the class.

Is this a sensible default since, `dotnet-isolated` is a new worker compared to `dotnet` for which backwards compatibility is required?
Compared to ASP.NET Core, when creating new webapi (`dotnet new webapi`), there is no usage of `static` keyword in files created by default.

**Comment by fabiocav** [comment]
Good question. Perhaps this is something we can get some feedback on... this matches the previous model for consistency, but we've created the issue you've linked to so we can have a review of all of the individual templates. This issue is one of the things we want to review, but we'll start the discussion there with more items (e.g. constructor injection for logger creation, nameof() in a few places where strings are being used, proper type usages based on what we'd recommend as a default, etc.)

**Comment by fabiocav** [comment]
This has been done for v4, so the experience targeting the new runtime now follows this recommendation.

Thanks!
