### ISSUE TITLE
Templates for Azure Functions On-Prem

### ISSUE THREAD

**Issue by slandsaw** [Azure/azure-functions-templates#676]
Is it possible to use any or all of the trigger templates for Azure functions on-prem? I'm working on a poc and could really use http and service bus topic triggers.

**Comment by paulbatum** [comment]
You can't use all of them. For example, there is no support for the HTTP triggered function in this configuration. I think you should be able to reuse the Service Bus Topic template though as I'm not aware of any issues with that in the on-prem config.

@apwestgarth @jvano Is there documentation somewhere that lists exactly what triggers are available in on-prem?

**Comment by jvano** [comment]
We don't have a list of available triggers and bindings since it is evident that we have a reduced list once you get into the Functions portal On-Premises.

Here is the list of tested triggers and bindings for the last release:

Triggers:
1. Timer
2. Queue
3. Blob

Bindings:
1. Queue
2. Blob
3. SQL Service Broker*

* Only available for On-Premises

NOTE: Other templates may work but we didn't include them because we didn't test them as part of the release.

**Comment by slandsaw** [comment]
I would like to point out that the available triggers do change depending on the configuration of the function app. This is what I have observed simple by changing the extension version from beta to ~1. 

Application setting | Value | Triggers
------------ | ------------- | -------------
FUNCTIONS_EXTENSION_VERSION | beta | Timer, Queue, Blob
FUNCTIONS_EXTENSION_VERSION | ~1 | Timer, Queue, Service Bus Queue, Blob, Event Hub, SQL Queue
