### ISSUE TITLE
Run Azure Functions v2 (.Net Core) with Empty template with updating "Azure Functions and Web Jobs Tools" to the latest version, an exception thrown about 'Microsoft.WindowsAzure.Storage.StorageException' in Output

### ISSUE THREAD

**Issue by phenning** [Azure/azure-functions-templates#777]
Reported by our vendor team (bug 706744)

**INSTALL STEPS:**
1. Win server 2012 R2 ENU : Clean machine
2. Install VSE Dev15.7.6 VSP(d15.7.27703.2047)

Select Web + Azure workload with 1.x tools checked

3. After initial installation, go to Tools -> Extensions and Updates > Updates >  Update "Azure Functions and Web Jobs Tools" to the latest version.(Version 15.10.2009.0)

**REPRO STEPS:**
1. After step 3 in INSTALL STEPS, open VS
2. File > New Project > Azure Functions >Azure Functions v2 (.Net Core) with Empty template + Storage Emulator selected.
3.Open Manage Nuget Packages to update the "Microsoft.NET.Sdk.Functions" verison to 1.0.22
4. Build works fine without any errors
5. F5, then func.exe will pop up, close it and verify the messages in Output - Debug : There is an exception thrown about 'Microsoft.WindowsAzure.Storage.StorageException'.

**Actual**

![untitled](https://user-images.githubusercontent.com/2433750/47174175-c1b3a900-d2c4-11e8-8b9e-137cb81c4f00.png)

[OutputInDebug.txt](https://github.com/Azure/azure-functions-templates/files/2493052/OutputInDebug.txt)

**Comment by phenning** [comment]
@paulbatum @soninaren 

This was reported by our CTI team and seems to be a problem with the CLI and not tooling.

**Comment by fabiocav** [comment]
@soninaren can we just validate whether this is still an issue?

**Comment by soninaren** [comment]
i was able to get the following exceptions when trying to repro the issue. i got the following exceptions. However the above exceptions are expected and are swallowed by the function runtime.
```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'Microsoft.WindowsAzure.Storage.StorageException' in System.Private.CoreLib.dll
```

FileNotFoundException is thrown because function runtime looks inside the bin directory for function.json file.
Microsoft.WindowsAzure.Storage.StorageException is cause by function runtime trying to obtain blob lease 

Both the exceptions are expected and the function runtime handles them They are still shown in the debug output since exception logging in vs was enabled by default. Also i don't see as many exceptions as shown in the screenshot above.
