### ISSUE TITLE
Access Rights field in New Function template is confusing

### ISSUE THREAD

**Issue by ColbyTresness** [Azure/azure-functions-templates#850]
_From @ggailey777 on March 27, 2018 21:57_

Customers have reported confusion about the **Access rights** field for an HTTP trigger Visual Studio:

![image](https://user-images.githubusercontent.com/1388263/37997149-f45a5ff8-31ce-11e8-8958-593274f66345.png)

This field is in both the new function and new function app template. Can we instead use **Authorization level**, so that it closer to the HTTP trigger metadata?

https://github.com/MicrosoftDocs/azure-docs/issues/5955

_Copied from original issue: Azure/Azure-Functions#739_

**Comment by ColbyTresness** [comment]
_From @Mike-EEE on March 28, 2018 10:40_

+1 to renaming to Authorization Level. Additionally, it would be incredibly useful to link to the documentation in regards to these levels.

Also, please consider renaming "Admin" to "Host" or "Host Key" to be consistent with the documentation.  If you use "Host Key", consider also renaming "Function" to "Function Key" to keep everything consistent.

**Comment by ColbyTresness** [comment]
_From @Mike-EEE on March 28, 2018 14:1_

I'm going to get myself in trouble here. 😆 

Been thinking about this a little more.  Another consideration might be something like this:

http://michael351.webflow.io/

This would be wrapped in a group control (which is not readily available at webflow, unfortunately) named `Security` and allows the user to select between all 3 states in a more intuitive manner (if I do say so myself LOL).

**Comment by ColbyTresness** [comment]
@nimakms  for VS

**Comment by ColbyTresness** [comment]
This actually comes from the templates repo, moving there.

**Comment by cbailiss** [comment]
+1 that this setting is confusing and a documentation link is needed.
Background:  I just tried creating an Azure function for the first time in VS.  I was (and still am) confused by this setting.  Googled the setting.  Found the issue in the old repo and followed it here - since it needs something (e.g. doc link) to make this understandable.  
"Anonymous" I can kind of guess what that means, but "Admin" is confusing (what kind of Admin?) and "Function" seems circular (i.e. I am creating an Azure function but it seems I can have/need another function [an Azure Function?] to handle auth).

**Comment by ggailey777** [comment]
Related issue: https://github.com/MicrosoftDocs/azure-docs/issues/5955

**Comment by ggailey777** [comment]
We did try to clarify this UI issue in the [VS quickstart](https://docs.microsoft.com/en-us/azure/azure-functions/functions-create-your-first-function-visual-studio#create-a-function-app-project):
![image](https://user-images.githubusercontent.com/1388263/55687737-418e0800-5925-11e9-8453-86aef4d111c6.png)
